# rename this file to zabbixFLFconfig.yml 
# default location: C:\Program Files\Zabbix Agent 2

commandMode: true
commandLine: C:\Temp\lsmon\lsmon\lsmon.exe
commandArguments: ms-tl-fap-dev1.ms.dev.local
commandResultWaitTimeSeconds: 0
localFile: C:\Temp\License.log
onlineUsersCounterConfig:
  - metricName: analyticsplatformonlineuserscount
    featureName: AnalyticsPlatform
  - metricName: pp_admonlineuserscount
    featureName: PP_Adm
  - metricName: pp_dashboardvieweronlineuserscount
    featureName: PP_DashboardViewer
  - metricName: pp_reportvieweronlineuserscount
    featureName: PP_ReportViewer
  - metricName: pp_dwdesigneronlineuserscount
    featureName: PP_DWDesigner
  - metricName: pp_dashboardeditoronlineuserscount
    featureName: PP_DashboardEditor
  - metricName: pp_scheduleronlineuserscount
    featureName: PP_Scheduler
