commandMode: false
commandLine: C:\Temp\lsmon\lsmon\lsmon.exe
localFile: C:\Temp\License.log
onlineUsersCounterConfig:
  - metricName: analyticsplatformonlineuserscount
    featureName: AnalyticsPlatform
  - metricName: pp_admonlineuserscount
    featureName: PP_Adm
  - metricName: pp_dashboardvieweronlineuserscount
    featureName: PP_DashboardViewer
  - metricName: pp_reportvieweronlineuserscount
    featureName: PP_ReportViewer
  - metricName: pp_dwdesigneronlineuserscount
    featureName: PP_DWDesigner
  - metricName: pp_dashboardeditoronlineuserscount
    featureName: PP_DashboardEditor
  - metricName: pp_scheduleronlineuserscount
    featureName: PP_Scheduler
